config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :purchases
  resources :stocks
  resources :carts
  resources :products do
    collection do
      get :shop
    end
  end
  resources :product_types
  resources :brands
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "products#index"
  get 'shop', to: 'products#shop'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :product_type
  has_one_attached :image
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def abbreviation
    first_name + " " + last_name
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ show edit update destroy ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:user_id, :description)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:cart_id, :deliver_option, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

    def show_image(product)
        if product.image.image?
          image_tag product.image, id: 'procedure-image', style:'height: 200px; width:auto'
        else
          image_tag "3", id: 'procedure-image'
        end
      end

    def price(product)
        if product.price != 0
          return product.price.to_s + "$"
        else
          return "Gratis"
        end
    end

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalIS3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/navbar" %>

    <div class="container padre">
      <%= yield %>
    </div>

    <%= render "shared/footer" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="container" style="margin-top: 30px">
    <nav class="navbar navbar-expand-xl navbar-light fixed-bottom" style="background-color: #937206;">
        <%= render "shared/user_menu" %>
    </nav>
</div>

app/views/shared/_menu.html.erb
<ul class="navbar-nav me-auto mb-2 mb-xl-0">
  <% if params[:action] == "shop" && params[:controller] == "products" %>
    <h1 style="color: white">Tienda ChauMosquitardo</h1>
  <% else %>
    <li class="nav-item">
      <%= link_to t('activerecord.models.brands'), brands_url, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to t('activerecord.models.product_types'), product_types_url, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to t('activerecord.models.stocks'), stocks_url, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to t('activerecord.models.products'), products_url, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to t('activerecord.models.purchases'), purchases_url, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to t('activerecord.models.orders'), orders_url, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to t('activerecord.models.carts'), carts_url, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to 'shop', shop_url, class: "nav-link active" %>
    </li>
  <% end %>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-xl navbar-dark" style="background-color: #003e7e;">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_url %>"><img src="https://cdn-icons-png.flaticon.com/512/4844/4844144.png" alt="Mosquito" width="40" height="40"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark"
      aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarDark">
      
      <%= render "shared/menu" %>

    </div>
  </div>
</nav>

app/views/shared/_user_menu.html.erb
<div class="btn-group dropup">
  <% if user_signed_in? %>
    <button type="button" class="btn dropdown-toggle ms-3" style="background-color: #efefef;" data-bs-toggle="dropdown" aria-expanded="false">
      <span style="color:black"><%= current_user.email %></span>
    </button>
    <ul class="dropdown-menu ms-3">
      <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %></li>
      <li><%= link_to "Log out", destroy_user_session_path, class: "dropdown-item",  method: :delete  %></li>
    </ul>
    <% else %>
      <%= link_to "Log in", new_user_session_url, class: 'btn btn-secondary ms-3' %>
    <% end %>
</div>